SELECT
    ID,
    (CASE 
        WHEN (DIFF / TOTAL) >= 0.75 THEN 'CRITICAL'
        WHEN (DIFF / TOTAL) >= 0.50 THEN 'HIGH'
        WHEN (DIFF / TOTAL) >= 0.25 THEN 'MEDIUM'
        ELSE 'LOW'
    END) AS COLONY_NAME
FROM (SELECT 
    E.ID AS ID,
    E.SIZE_OF_COLONY AS SIZE,
    (SELECT 
        COUNT(*) 
    FROM ECOLI_DATA EE 
    WHERE 
     EE.SIZE_OF_COLONY < E.SIZE_OF_COLONY
    ) AS DIFF,
    COUNT(*) OVER() AS TOTAL
FROM ECOLI_DATA E) AS ECOLI_DATA
ORDER BY
    ID


    