   console.log(15000 - new Set(require('fs')
    .readFileSync(process.platform === 'linux' ? 0 : './input.txt', 'utf-8')
    .toString()
    .trim()
    .split('\n')
    .slice(1)
    .at(0)
    .split(' ')
    .map(Number))
    .size)