SELECT 
    I.ID AS ID, 
    N.FISH_NAME AS FISH_NAME, 
    I.LENGTH AS LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N 
    ON I.FISH_TYPE = N.FISH_TYPE 
WHERE I.ID = (
    SELECT I2.ID 
    FROM FISH_INFO I2 
    WHERE I2.FISH_TYPE = I.FISH_TYPE 
    ORDER BY 
        CASE 
            WHEN I2.LENGTH IS NULL THEN 10 
            WHEN I2.LENGTH <= 10 THEN 10 
            ELSE I2.LENGTH 
        END DESC, 
        I2.ID ASC 
    LIMIT 1
);