SELECT 
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
LEFT JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
LEFT JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID
WHERE G.YEAR = '2022'
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SCORE DESC
LIMIT 1;