-- 코드를 입력하세요
SELECT
    B.CATEGORY AS CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    BOOK_SALES S
JOIN
    BOOK B
    ON S.BOOK_ID = B.BOOK_ID
WHERE
    DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY ASC